import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "next-themes";
import configuration from "@/../configuration/configuration";
import { Layout } from "@/components/layout/layout";
import SearchDialog from "@/components/dialog/search";
// import { DndContext } from "@dnd-kit/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by DataVis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          disableTransitionOnChange
          attribute="class"
          enableSystem
          defaultTheme={configuration.userConfiguration.defaultColorMode}
        >
          <main>
            <Layout>{children}</Layout>
            <SearchDialog />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
